README.md, examples/examplelibrary/listshelves.go, examples/examplelibrary/listshelves_test.go, pagination/pagetoken.go, pagination/pagetoken_test.go, resourceid/systemgenerated.go, resourceid/systemgenerated_test.go
Semantically equivalent to a UUIDv4 but with a more compact, yet still
readable encoding.
=> feat: add resourceid.NewSystemGeneratedBase32()

pagination/pagetoken.go, pagination/pagetoken_test.go, pagination/struct.go, pagination/struct_test.go
Useful for page tokens that don't conform to the offset/checksum
standard.
=> feat(pagination): expose Gob transcoding

fieldmask/validate.go, fieldmask/validate_test.go
Special '*' path is valid, even if message does not contain a field with
that path. It can not be combined with other paths.
=> feat: support star in fieldmask.Validate

filtering/checker.go, filtering/checker_test.go, filtering/errors.go, filtering/filter.go, filtering/functions.go, filtering/macro.go, filtering/macro_test.go, filtering/request.go, filtering/walk.go
Enables rewriting of the filter expression, and re-checking types
against a separate set of declarations.
Useful when rewriting an expression for use in transpilation to a
database filter.
=> feat(filtering): initial support for macros

fieldbehavior/fieldbehavior_test.go, fieldbehavior/required.go
From https://google.aip.dev/134:
> If optional [fieldmask], the service must treat an omitted field mask
> as an implied field mask equivalent to all fields that are set on the wire.
This is a breaking change, to keep the previous behavior:
- Replace the empty (or nil) fieldmask with "*"
=> fix!: tŕeat empty field mask as equivalent to wire-set fields

resourcename/sscan.go, resourcename/sscan_test.go
Similar API to fmt.Sscanf but for resource names and patterns.
Scans a resource name and stores variable segments to string variables.
Useful for implementing resource name parsing.
=> feat: add resourcename.Scan

resourcename/sprint.go, resourcename/sprint_test.go
Formats a resource name string from a pattern and variables, with
similar API as fmt.Sprintf.
=> feat: add resourcename.Sprint

resourcename/matches.go, resourcename/matches_test.go
For parity with regexp.Match, also reorderes the arguments to put the
pattern first.
=> feat: rename resourcename.Matches to resourcename.Match

resourcename/sprint.go
Copy-paste error from `fmt` package.
=> fix: update comment of resourcename.Sprint to correct method

filtering/checker.go
Adding this information reduces time needed to debug these kinds of
issues.
=> fix: improve error message when no matching overload found

filtering/parser.go, filtering/parser_test.go
Previously nested AND expressions (ex: "a AND b AND c") would not set an
ID on the innermost AND expression. This commit changes the "folding" of
a sequence of AND expressions to be similar to OR expressions.
Also adds a test to ensure that all tested expressions produce
subexpressions with unique IDs.
This fixes an issue where type checking fails because of duplicate IDs.
=> fix(filtering): set expr.ID on nested AND expressions

filtering/macro.go
Next ID was never updated when a macro replaced a subexpression, leading
to duplicate IDs down the line.
=> fix(filtering): always increment next id when applying macros

resourcename/hasparent.go, resourcename/hasparent_test.go, resourcename/rangeparents.go, resourcename/rangeparents_test.go, resourcename/scanner.go
Returns every possible parent, including collection segments.
Useful for resolving IAM permissions without further knowledge of
patterns for specific resource names.
=> feat: add resourcename.RangeParents

resourcename/isdomainname.go, resourcename/validate.go, resourcename/validate_test.go
Includes a copied implementation of the not-yet-public (due to some edge
cases) implementation of domain name validation in go/src/net.
=> feat: add resourcename.Validate

fieldmask/update.go, fieldmask/update_test.go
Previously when calling `Update` with paths in the fieldmask which
covered message fields, this method would allocate a new empty message
instead of nil.
Concretely this meant that timestamps could not be properly unset with a
fieldmask, as they would not become nil but rather `{ Seconds: 0, Nanos:
0}` which is a valid timestamp.
This also changes how oneofs are Updated when the source does not
specify a kind. This is the correct behavior.
=> fix(fieldmask): dont populate message type when updating from nil

validation/error.go, validation/error_test.go
Start lines related to the same error with `|` to increase readability.
=> feat(validation): improve error presentation

filtering/exprs/doc.go, filtering/exprs/match.go, filtering/exprs/match_example_test.go, filtering/exprs/match_test.go
When using filters in APIs it is typical to validate the filter (for
example resource names) and transform it to a database schema.
The `filtering` package already exposes functionality for walking
(`filtering.Walk`) and transforming (`filtering.ApplyMacros`) exprs.
When using either of those methods some functions should be applied to
only parts of the expression tree, which typically results multiple if
statements parsing the expression.
The `exprs` package exposes several `Matcher` functions which can be
used to match parts of the expression tree. See the Go example for an
example use case.
=> feat(filtering/exprs): package for working with exprs

resourceid/usersettable.go, resourceid/usersettable_test.go
Add additional checks to conform to RFC-1034, i.e.,
user-settable resource ID must begin with a letter and
end with a letter or number.
See aip-dev/google.aip.dev#724 for the clarification.
=> fix(resourceid): update ValidateUserSettable

filtering/declarations.go
Previously we only supported equals operation on enums. This PR adds support for not equals as well.﻿
=> feat(enums): add support for not equals functions on enums

.github/workflows/ci.yml, .golangci.yml
this is needed when for example dependabot merges a PR.
Also downgraded Go to 1.15 to match the minimum required version in the go.mod file.
Maybe we should add a matrix step to test 15, 16, and 17 perhaps?
_Also disabled replaced/deprecated linters_
=> fix(ci): allow users without write permissions to make releases

resourcename/matches_test.go, resourcename/scanner.go
when the resourcename pattern starts with a single slash we got into a corner case where the matcher would loop infinitely.
=> fix(resourcename): inifinite loop on certain pattern

cmd/protoc-gen-go-aip/internal/genaip/resourcename.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/single/testdata.proto, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/single/testdata_aip.go, proto/gen/einride/example/freight/v1/shipment_aip.go, proto/gen/einride/example/freight/v1/site_aip.go
When a resource name has a parent, one often has the parent variable
lying around and the child needs to be created. Instead of having to
repeat all of the fields when constructing the child type, if we have
access to constructor methods that receive the parent struct we can save
some effort.
Before some code might look like:
```
shelf := ShelfResourceName{Shelf: "bottom"}
book := BookResourceName{Shelf: "bottom", Book: "Harry Potter"}
```
Now the code can do this:
```
shelf := ShelfResourceName{Shelf: "bottom"}
book := shelf.BookResourceName("Harry Potter")
```
=> feat: generate constructor methods for resource name types

filtering/checker.go, filtering/checker_test.go, filtering/functions.go
If a timestamp field is used in a comparison function with a string,
perform a validation that the string in a timestamp formatted in RFC3339
format as AIP spec
=> feat: add support for comparing timestamps as strings

cmd/protoc-gen-go-aip/internal/genaip/resourcename.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/multipattern/pattern_test.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/multipattern/testdata.proto, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/multipattern/testdata_aip.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/originallysinglepattern/pattern_test.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/originallysinglepattern/testdata.proto, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/originallysinglepattern/testdata_aip.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/single/pattern_test.go
For top-level resources, multi-pattern resource names causes the generation of two identical structs as the multi-pattern struct of the first pattern is identical to the single-pattern struct.
See added Shelf resources and accompanying test cases which reproduces the issue without the fix.
To validate this doesn't break existing behavior, the first commit introduces some regression tests.
=> fix: avoid generating single-pattern struct twice

pagination/pagetoken.go, pagination/pagetoken_test.go
BREAKING CHANGE: This will result in a different response if
next_page_token have been used in combination with skip.
=> fix: respect pagination skip field

examples/examplelibrary/listshelves_test.go
The page token value changes as of Go 1.21, likely due to changes in Gob encoding. Old values should still be unmarshaled properly by Go 1.21, so shouldn't be an issue.
Avoid asserting on the exact page token value in a test, and instead log if it is empty or not, as the test will produce different outputs depending on the Go version used.
=> fix: avoid asserting on exact page token value

resourcename/join.go, resourcename/join_test.go
Join combines resource names, separating them by slashes.
Currently supports leading slashes on each resource names, discussion on that to be held in [#258].
[#258]: https://github.com/einride/aip-go/pull/258
=> feat(resourcename): add Join function

cmd/protoc-gen-go-aip/internal/genaip/resourcename.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/multipattern/testdata_aip.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/originallysinglepattern/testdata_aip.go
Resource name structs have a ContainsWildcard() method. To simplify checking this on multi-pattern resource names, exposing this on the multipattern interface makes it easy to check without figuring out the underlying type first.
=> feat(protoc): expose ContainsWildcard on multipattern

.sage/main.go
=> fix: bump golang.org/x/tools/cmd/stringer to 0.20.0

cmd/protoc-gen-go-aip/internal/genaip/resourcename.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/multipattern/testdata_aip.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/originallysinglepattern/testdata_aip.go, cmd/protoc-gen-go-aip/internal/genaip/testdata/test/single/testdata_aip.go, proto/gen/einride/example/freight/v1/shipment_aip.go, proto/gen/einride/example/freight/v1/shipper_aip.go, proto/gen/einride/example/freight/v1/site_aip.go
We are calling `Validate()` on marshalling but not on unmarshalling a resource name. This PR fixes that.
=> Call Validate() when unmarshalling resource name

.sage/go.mod, .sage/go.sum, filtering/lexer.go, filtering/macro.go
Linter fixes:
* ignore G115 in filtering/lexer
Not likely that `n` (width of a rune) is large enough to overflow an int32.
* rename variable to avoid shadowing built-in function
Pleases the predeclared linter.
=> chore(sage): bump to v0.306.0

README.md
- **docs: remove link to AIP docs, mentioned on the line above**
- **docs: be more clear about library usage**
- **docs: add separate section on codegen from proto**
=> docs: improve usage examples

README.md
This was probably intended to be a tab character.
=> fix: remove erroneous section character in README.md

filtering/lexer.go, filtering/parser.go, filtering/parser_test.go, filtering/token.go, filtering/unescape.go, filtering/unescape_test.go
The `filtering` package now correctly handles (un)escaping of strings. I used https://github.com/google/cel-spec/blob/master/doc/langdef.md#string-and-bytes-values and https://github.com/google/cel-go/blob/master/parser/unescape.go to solve this.
=> fix(filtering): correctly unescape strings

resourceid/usersettable.go, resourceid/usersettable_test.go
Since this [PR](https://github.com/aip-dev/google.aip.dev/pull/1491),
usersettable id can now take the form of an UUID, this commit reflects
that.
=> feat(usersettable): allow id to have the form of an uuid
